export const TOURNAMENTS_GET = 'TOURNAMENTS_GET';
export const TOURNAMENTS_GET_SUCCESS = 'TOURNAMENTS_GET_SUCCESS';
export const TOURNAMENTS_GET_ERROR = 'TOURNAMENTS_GET_ERROR';

export const TOURNAMENTS_DELETE = 'TOURNAMENTS_DELETE';
export const TOURNAMENTS_EDIT = 'TOURNAMENTS_EDIT';
export const TOURNAMENTS_CREATE = 'TOURNAMENTS_CREATE';
